version: '2'
services:
  magento:
    image: procrypto/magento
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    depends_on: 
      - mysql
    env_file:
      - env
  db:
    image: postgres:9.4
    ports:
     - "5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
  odo:
    image: procrypto/odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_ENV_POSTGRES_USER=odoo
      - DB_ENV_POSTGRES_PASSWORD=odoo
  mysql:
    image: mysql:5.6.23
    ports: 
     - "3306"
    env_file:
      - env
